### ISSUE TITLE
Full permission

### ISSUE THREAD

**Issue by AhmedYasser27** [brightkan/solitonEMS#117]
Dears Good day how can i give  Full authorization permission to open all modules , thanks in advance.

**Comment by AhmedYasser27** [comment]
![Capture](https://user-images.githubusercontent.com/63955840/87253440-83d4bc00-c47b-11ea-8637-3653d6537999.PNG)

**Comment by AhmedYasser27** [comment]
any solution Dears

**Comment by brightkan** [comment]
Permissions have been removed

**Comment by AhmedYasser27** [comment]
Thanks Dear For Your Great efforts.
